name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build and publish gem
      uses: jstastny/publish-gem-to-github@master
      continue-on-error: true
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        owner: johnallen3d
